name: CI/CD to Render

on:
  push:
    branches: ["main"]

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - name: Chechout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        
      - name: Install dependancies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -c "from app import app; print('App imported successfully')"

  build-and-push:
    name: Build and push to GHCR
    runs-on: ubuntu-latest
    needs: test-python
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Chechout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/prakt_git_devops1/my-python-app:latest
            ghcr.io/prakt_git_devops1/my-python-app:${{github.sha}}